package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRpLike<M extends BaseRpLike<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setNo(java.lang.Integer no) {
		set("no", no);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getNo() {
		return getInt("no");
	}

	/**
	 * 编号，对应rp建议编号
	 */
	public M setRpNum(java.lang.String rpNum) {
		set("rp_num", rpNum);
		return (M)this;
	}
	
	/**
	 * 编号，对应rp建议编号
	 */
	public java.lang.String getRpNum() {
		return getStr("rp_num");
	}

	/**
	 * 发布日期
	 */
	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	/**
	 * 发布日期
	 */
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	/**
	 * 用户id
	 */
	public M setUserid(java.lang.String userid) {
		set("userid", userid);
		return (M)this;
	}
	
	/**
	 * 用户id
	 */
	public java.lang.String getUserid() {
		return getStr("userid");
	}

	/**
	 * 是否赞，0=否或取消，1=赞
	 */
	public M setIsLike(java.lang.Integer isLike) {
		set("isLike", isLike);
		return (M)this;
	}
	
	/**
	 * 是否赞，0=否或取消，1=赞
	 */
	public java.lang.Integer getIsLike() {
		return getInt("isLike");
	}

}
