package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSerialNumber<M extends BaseSerialNumber<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 收货单号
	 */
	public M setPartInvoiceNo(java.lang.Integer partInvoiceNo) {
		set("part_invoice_no", partInvoiceNo);
		return (M)this;
	}
	
	/**
	 * 收货单号
	 */
	public java.lang.Integer getPartInvoiceNo() {
		return getInt("part_invoice_no");
	}

	/**
	 * 检验单号
	 */
	public M setPartCheckNo(java.lang.Integer partCheckNo) {
		set("part_check_no", partCheckNo);
		return (M)this;
	}
	
	/**
	 * 检验单号
	 */
	public java.lang.Integer getPartCheckNo() {
		return getInt("part_check_no");
	}

	/**
	 * 配料单号
	 */
	public M setIngredientPlanNo(java.lang.Integer ingredientPlanNo) {
		set("ingredient_plan_no", ingredientPlanNo);
		return (M)this;
	}
	
	/**
	 * 配料单号
	 */
	public java.lang.Integer getIngredientPlanNo() {
		return getInt("ingredient_plan_no");
	}

	/**
	 * 客户订单号
	 */
	public M setCustOrderNo(java.lang.Integer custOrderNo) {
		set("cust_order_no", custOrderNo);
		return (M)this;
	}
	
	/**
	 * 客户订单号
	 */
	public java.lang.Integer getCustOrderNo() {
		return getInt("cust_order_no");
	}

	/**
	 * 电磁阀库存序号
	 */
	public M setValveInvNo(java.lang.Integer valveInvNo) {
		set("valve_inv_no", valveInvNo);
		return (M)this;
	}
	
	/**
	 * 电磁阀库存序号
	 */
	public java.lang.Integer getValveInvNo() {
		return getInt("valve_inv_no");
	}

}
