package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDataButton<M extends BaseDataButton<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 元数据ID
	 */
	public M setDataObjectId(java.lang.Integer dataObjectId) {
		set("data_object_id", dataObjectId);
		return (M)this;
	}
	
	/**
	 * 元数据ID
	 */
	public java.lang.Integer getDataObjectId() {
		return getInt("data_object_id");
	}

	/**
	 * 按钮位置:1=头部,2=行内
	 */
	public M setLocation(java.lang.Integer location) {
		set("location", location);
		return (M)this;
	}
	
	/**
	 * 按钮位置:1=头部,2=行内
	 */
	public java.lang.Integer getLocation() {
		return getInt("location");
	}

	/**
	 * 按钮类型:1=confirm,2=combobox
	 */
	public M setType(java.lang.Integer type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 按钮类型:1=confirm,2=combobox
	 */
	public java.lang.Integer getType() {
		return getInt("type");
	}

	/**
	 * 按钮排序
	 */
	public M setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}
	
	/**
	 * 按钮排序
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}

	/**
	 * 按钮图标
	 */
	public M setIcon(java.lang.String icon) {
		set("icon", icon);
		return (M)this;
	}
	
	/**
	 * 按钮图标
	 */
	public java.lang.String getIcon() {
		return getStr("icon");
	}

	/**
	 * 按钮名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 按钮名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 按钮样式
	 */
	public M setColor(java.lang.String color) {
		set("color", color);
		return (M)this;
	}
	
	/**
	 * 按钮样式
	 */
	public java.lang.String getColor() {
		return getStr("color");
	}

	/**
	 * 按钮提示信息
	 */
	public M setTip(java.lang.String tip) {
		set("tip", tip);
		return (M)this;
	}
	
	/**
	 * 按钮提示信息
	 */
	public java.lang.String getTip() {
		return getStr("tip");
	}

	/**
	 * dialog标题
	 */
	public M setDialogTitle(java.lang.String dialogTitle) {
		set("dialog_title", dialogTitle);
		return (M)this;
	}
	
	/**
	 * dialog标题
	 */
	public java.lang.String getDialogTitle() {
		return getStr("dialog_title");
	}

	/**
	 * dialog宽度
	 */
	public M setDialogWidth(java.lang.String dialogWidth) {
		set("dialog_width", dialogWidth);
		return (M)this;
	}
	
	/**
	 * dialog宽度
	 */
	public java.lang.String getDialogWidth() {
		return getStr("dialog_width");
	}

	/**
	 * dialog高度
	 */
	public M setDialogHeight(java.lang.String dialogHeight) {
		set("dialog_height", dialogHeight);
		return (M)this;
	}
	
	/**
	 * dialog高度
	 */
	public java.lang.String getDialogHeight() {
		return getStr("dialog_height");
	}

	/**
	 * dialog地址
	 */
	public M setDialogSrc(java.lang.String dialogSrc) {
		set("dialog_src", dialogSrc);
		return (M)this;
	}
	
	/**
	 * dialog地址
	 */
	public java.lang.String getDialogSrc() {
		return getStr("dialog_src");
	}

	/**
	 * 按钮访问后端action
	 */
	public M setAction(java.lang.String action) {
		set("action", action);
		return (M)this;
	}
	
	/**
	 * 按钮访问后端action
	 */
	public java.lang.String getAction() {
		return getStr("action");
	}

	/**
	 * 角色标识权限集合
	 */
	public M setAuthRole(java.lang.String authRole) {
		set("auth_role", authRole);
		return (M)this;
	}
	
	/**
	 * 角色标识权限集合
	 */
	public java.lang.String getAuthRole() {
		return getStr("auth_role");
	}

	/**
	 * 行内权限
	 */
	public M setAuthRow(java.lang.String authRow) {
		set("auth_row", authRow);
		return (M)this;
	}
	
	/**
	 * 行内权限
	 */
	public java.lang.String getAuthRow() {
		return getStr("auth_row");
	}

	/**
	 * 是否显示
	 */
	public M setIsShow(java.lang.Boolean isShow) {
		set("is_show", isShow);
		return (M)this;
	}
	
	/**
	 * 是否显示
	 */
	public java.lang.Boolean getIsShow() {
		return getBoolean("is_show");
	}

}
