package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDataObject<M extends BaseDataObject<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 表名
	 */
	public M setTableName(java.lang.String tableName) {
		set("table_name", tableName);
		return (M)this;
	}
	
	/**
	 * 表名
	 */
	public java.lang.String getTableName() {
		return getStr("table_name");
	}

	/**
	 * 英文编码
	 */
	public M setEn(java.lang.String en) {
		set("en", en);
		return (M)this;
	}
	
	/**
	 * 英文编码
	 */
	public java.lang.String getEn() {
		return getStr("en");
	}

	/**
	 * 中文名
	 */
	public M setCn(java.lang.String cn) {
		set("cn", cn);
		return (M)this;
	}
	
	/**
	 * 中文名
	 */
	public java.lang.String getCn() {
		return getStr("cn");
	}

	/**
	 * 查询表达式
	 */
	public M setWhereAttr(java.lang.String whereAttr) {
		set("where_attr", whereAttr);
		return (M)this;
	}
	
	/**
	 * 查询表达式
	 */
	public java.lang.String getWhereAttr() {
		return getStr("where_attr");
	}

	/**
	 * 拦截器
	 */
	public M setInterceptor(java.lang.String interceptor) {
		set("interceptor", interceptor);
		return (M)this;
	}
	
	/**
	 * 拦截器
	 */
	public java.lang.String getInterceptor() {
		return getStr("interceptor");
	}

	/**
	 * 是否新增
	 */
	public M setIsAdd(java.lang.Boolean isAdd) {
		set("is_add", isAdd);
		return (M)this;
	}
	
	/**
	 * 是否新增
	 */
	public java.lang.Boolean getIsAdd() {
		return getBoolean("is_add");
	}

	/**
	 * 是否修改
	 */
	public M setIsUpdate(java.lang.Boolean isUpdate) {
		set("is_update", isUpdate);
		return (M)this;
	}
	
	/**
	 * 是否修改
	 */
	public java.lang.Boolean getIsUpdate() {
		return getBoolean("is_update");
	}

	/**
	 * 是否可行内修改
	 */
	public M setIsLineUpdate(java.lang.Boolean isLineUpdate) {
		set("is_line_update", isLineUpdate);
		return (M)this;
	}
	
	/**
	 * 是否可行内修改
	 */
	public java.lang.Boolean getIsLineUpdate() {
		return getBoolean("is_line_update");
	}

	/**
	 * 是否删除
	 */
	public M setIsDelete(java.lang.Boolean isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}
	
	/**
	 * 是否删除
	 */
	public java.lang.Boolean getIsDelete() {
		return getBoolean("is_delete");
	}

	/**
	 * 是否拥有操作列
	 */
	public M setIsHandle(java.lang.Boolean isHandle) {
		set("is_handle", isHandle);
		return (M)this;
	}
	
	/**
	 * 是否拥有操作列
	 */
	public java.lang.Boolean getIsHandle() {
		return getBoolean("is_handle");
	}

	/**
	 * 操作列宽度
	 */
	public M setHandleWidth(java.lang.String handleWidth) {
		set("handle_width", handleWidth);
		return (M)this;
	}
	
	/**
	 * 操作列宽度
	 */
	public java.lang.String getHandleWidth() {
		return getStr("handle_width");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
