package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseS6sHandlers<M extends BaseS6sHandlers<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 区域名称
	 */
	public M setDisName(java.lang.String disName) {
		set("dis_name", disName);
		return (M)this;
	}
	
	/**
	 * 区域名称
	 */
	public java.lang.String getDisName() {
		return getStr("dis_name");
	}

	public M setDisId(java.lang.Integer disId) {
		set("dis_id", disId);
		return (M)this;
	}
	
	public java.lang.Integer getDisId() {
		return getInt("dis_id");
	}

	/**
	 * 处理人
	 */
	public M setPName(java.lang.String pName) {
		set("p_name", pName);
		return (M)this;
	}
	
	/**
	 * 处理人
	 */
	public java.lang.String getPName() {
		return getStr("p_name");
	}

	/**
	 * 处理人工号
	 */
	public M setPJobNumber(java.lang.String pJobNumber) {
		set("p_job_number", pJobNumber);
		return (M)this;
	}
	
	/**
	 * 处理人工号
	 */
	public java.lang.String getPJobNumber() {
		return getStr("p_job_number");
	}

	/**
	 * 处理人手机号
	 */
	public M setPhone(java.lang.String phone) {
		set("phone", phone);
		return (M)this;
	}
	
	/**
	 * 处理人手机号
	 */
	public java.lang.String getPhone() {
		return getStr("phone");
	}

}
