package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePp<M extends BasePp<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 员工姓名
	 */
	public M setUserName(java.lang.String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	/**
	 * 员工姓名
	 */
	public java.lang.String getUserName() {
		return getStr("user_name");
	}

	/**
	 * 员工工号
	 */
	public M setUserJobNumber(java.lang.String userJobNumber) {
		set("user_job_number", userJobNumber);
		return (M)this;
	}
	
	/**
	 * 员工工号
	 */
	public java.lang.String getUserJobNumber() {
		return getStr("user_job_number");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 事业部
	 */
	public M setDepartment(java.lang.String department) {
		set("department", department);
		return (M)this;
	}
	
	/**
	 * 事业部
	 */
	public java.lang.String getDepartment() {
		return getStr("department");
	}

	/**
	 * 车间
	 */
	public M setWorkshop(java.lang.String workshop) {
		set("workshop", workshop);
		return (M)this;
	}
	
	/**
	 * 车间
	 */
	public java.lang.String getWorkshop() {
		return getStr("workshop");
	}

	/**
	 * 产线
	 */
	public M setProductionLine(java.lang.String productionLine) {
		set("production_line", productionLine);
		return (M)this;
	}
	
	/**
	 * 产线
	 */
	public java.lang.String getProductionLine() {
		return getStr("production_line");
	}

	/**
	 * 班长姓名
	 */
	public M setLeaderName(java.lang.String leaderName) {
		set("leader_name", leaderName);
		return (M)this;
	}
	
	/**
	 * 班长姓名
	 */
	public java.lang.String getLeaderName() {
		return getStr("leader_name");
	}

	/**
	 * 出勤日期
	 */
	public M setWorkDate(java.util.Date workDate) {
		set("work_date", workDate);
		return (M)this;
	}
	
	/**
	 * 出勤日期
	 */
	public java.util.Date getWorkDate() {
		return get("work_date");
	}

	/**
	 * 出勤时长
	 */
	public M setWorkTime(java.lang.Float workTime) {
		set("work_time", workTime);
		return (M)this;
	}
	
	/**
	 * 出勤时长
	 */
	public java.lang.Float getWorkTime() {
		return getFloat("work_time");
	}

	/**
	 * 班次
	 */
	public M setShifts(java.lang.String shifts) {
		set("shifts", shifts);
		return (M)this;
	}
	
	/**
	 * 班次
	 */
	public java.lang.String getShifts() {
		return getStr("shifts");
	}

	/**
	 * 产品名称
	 */
	public M setPdName(java.lang.String pdName) {
		set("pd_name", pdName);
		return (M)this;
	}
	
	/**
	 * 产品名称
	 */
	public java.lang.String getPdName() {
		return getStr("pd_name");
	}

	/**
	 * 产品编号
	 */
	public M setPdNo(java.lang.String pdNo) {
		set("pd_no", pdNo);
		return (M)this;
	}
	
	/**
	 * 产品编号
	 */
	public java.lang.String getPdNo() {
		return getStr("pd_no");
	}

	/**
	 * 零件名称
	 */
	public M setPartName(java.lang.String partName) {
		set("part_name", partName);
		return (M)this;
	}
	
	/**
	 * 零件名称
	 */
	public java.lang.String getPartName() {
		return getStr("part_name");
	}

	/**
	 * 零件编号
	 */
	public M setPartNo(java.lang.String partNo) {
		set("part_no", partNo);
		return (M)this;
	}
	
	/**
	 * 零件编号
	 */
	public java.lang.String getPartNo() {
		return getStr("part_no");
	}

	/**
	 * 工序名称
	 */
	public M setProcessName(java.lang.String processName) {
		set("process_name", processName);
		return (M)this;
	}
	
	/**
	 * 工序名称
	 */
	public java.lang.String getProcessName() {
		return getStr("process_name");
	}

	/**
	 * 工序编号
	 */
	public M setProcessNo(java.lang.String processNo) {
		set("process_no", processNo);
		return (M)this;
	}
	
	/**
	 * 工序编号
	 */
	public java.lang.String getProcessNo() {
		return getStr("process_no");
	}

	/**
	 * 人工小时产量
	 */
	public M setLaborRunFactor(java.lang.Float laborRunFactor) {
		set("labor_run_factor", laborRunFactor);
		return (M)this;
	}
	
	/**
	 * 人工小时产量
	 */
	public java.lang.Float getLaborRunFactor() {
		return getFloat("labor_run_factor");
	}

	/**
	 * 设备编号
	 */
	public M setEquipNo(java.lang.String equipNo) {
		set("equip_no", equipNo);
		return (M)this;
	}
	
	/**
	 * 设备编号
	 */
	public java.lang.String getEquipNo() {
		return getStr("equip_no");
	}

	/**
	 * 合格数量
	 */
	public M setQualifiedQty(java.lang.Integer qualifiedQty) {
		set("qualified_qty", qualifiedQty);
		return (M)this;
	}
	
	/**
	 * 合格数量
	 */
	public java.lang.Integer getQualifiedQty() {
		return getInt("qualified_qty");
	}

	/**
	 * 不合格数量
	 */
	public M setUnqualifiedQty(java.lang.Integer unqualifiedQty) {
		set("unqualified_qty", unqualifiedQty);
		return (M)this;
	}
	
	/**
	 * 不合格数量
	 */
	public java.lang.Integer getUnqualifiedQty() {
		return getInt("unqualified_qty");
	}

	/**
	 * 不合格原因
	 */
	public M setUnqualifiedReason(java.lang.String unqualifiedReason) {
		set("unqualified_reason", unqualifiedReason);
		return (M)this;
	}
	
	/**
	 * 不合格原因
	 */
	public java.lang.String getUnqualifiedReason() {
		return getStr("unqualified_reason");
	}

	/**
	 * 无效工时
	 */
	public M setInvalidManHour(java.lang.Integer invalidManHour) {
		set("invalid_man_hour", invalidManHour);
		return (M)this;
	}
	
	/**
	 * 无效工时
	 */
	public java.lang.Integer getInvalidManHour() {
		return getInt("invalid_man_hour");
	}

	/**
	 * 问题
	 */
	public M setQuestions(java.lang.String questions) {
		set("questions", questions);
		return (M)this;
	}
	
	/**
	 * 问题
	 */
	public java.lang.String getQuestions() {
		return getStr("questions");
	}

	/**
	 * 备注
	 */
	public M setNote(java.lang.String note) {
		set("note", note);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

}
