package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 登录账号
	 */
	public M setUsername(java.lang.String username) {
		set("username", username);
		return (M)this;
	}
	
	/**
	 * 登录账号
	 */
	public java.lang.String getUsername() {
		return getStr("username");
	}

	/**
	 * 登录密码
	 */
	public M setPassword(java.lang.String password) {
		set("password", password);
		return (M)this;
	}
	
	/**
	 * 登录密码
	 */
	public java.lang.String getPassword() {
		return getStr("password");
	}

	/**
	 * 用户姓名
	 */
	public M setNickname(java.lang.String nickname) {
		set("nickname", nickname);
		return (M)this;
	}
	
	/**
	 * 用户姓名
	 */
	public java.lang.String getNickname() {
		return getStr("nickname");
	}

	/**
	 * 钉钉USERID
	 */
	public M setDingUserId(java.lang.String dingUserId) {
		set("ding_user_id", dingUserId);
		return (M)this;
	}
	
	/**
	 * 钉钉USERID
	 */
	public java.lang.String getDingUserId() {
		return getStr("ding_user_id");
	}

	/**
	 * 修改时间
	 */
	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 权限：0无，1钉钉后台，2优秀建议审核权
	 */
	public M setRights(java.lang.String rights) {
		set("rights", rights);
		return (M)this;
	}
	
	/**
	 * 权限：0无，1钉钉后台，2优秀建议审核权
	 */
	public java.lang.String getRights() {
		return getStr("rights");
	}

	/**
	 * 工号
	 */
	public M setJobNumber(java.lang.String jobNumber) {
		set("job_number", jobNumber);
		return (M)this;
	}
	
	/**
	 * 工号
	 */
	public java.lang.String getJobNumber() {
		return getStr("job_number");
	}

}
