package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRpComment<M extends BaseRpComment<M>> extends Model<M> implements IBean {

	/**
	 * 评论id
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 评论id
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 合理化建议序号id
	 */
	public M setRpNumb(java.lang.String rpNumb) {
		set("rp_numb", rpNumb);
		return (M)this;
	}
	
	/**
	 * 合理化建议序号id
	 */
	public java.lang.String getRpNumb() {
		return getStr("rp_numb");
	}

	/**
	 * 评论人工号
	 */
	public M setCommentUserid(java.lang.String commentUserid) {
		set("comment_userid", commentUserid);
		return (M)this;
	}
	
	/**
	 * 评论人工号
	 */
	public java.lang.String getCommentUserid() {
		return getStr("comment_userid");
	}

	/**
	 * 评论人姓名
	 */
	public M setCommentUsername(java.lang.String commentUsername) {
		set("comment_username", commentUsername);
		return (M)this;
	}
	
	/**
	 * 评论人姓名
	 */
	public java.lang.String getCommentUsername() {
		return getStr("comment_username");
	}

	/**
	 * 评论内容
	 */
	public M setCommentContent(java.lang.String commentContent) {
		set("comment_content", commentContent);
		return (M)this;
	}
	
	/**
	 * 评论内容
	 */
	public java.lang.String getCommentContent() {
		return getStr("comment_content");
	}

	/**
	 * 评论日期
	 */
	public M setCommentCreateDate(java.util.Date commentCreateDate) {
		set("comment_create_date", commentCreateDate);
		return (M)this;
	}
	
	/**
	 * 评论日期
	 */
	public java.util.Date getCommentCreateDate() {
		return get("comment_create_date");
	}

	/**
	 * 是否有评论
	 */
	public M setIsComment(java.lang.Integer isComment) {
		set("isComment", isComment);
		return (M)this;
	}
	
	/**
	 * 是否有评论
	 */
	public java.lang.Integer getIsComment() {
		return getInt("isComment");
	}

}
