package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseS6sAwardRecord<M extends BaseS6sAwardRecord<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 区域
	 */
	public M setDistrict(java.lang.String district) {
		set("district", district);
		return (M)this;
	}
	
	/**
	 * 区域
	 */
	public java.lang.String getDistrict() {
		return getStr("district");
	}

	/**
	 * 员工姓名
	 */
	public M setPName(java.lang.String pName) {
		set("p_name", pName);
		return (M)this;
	}
	
	/**
	 * 员工姓名
	 */
	public java.lang.String getPName() {
		return getStr("p_name");
	}

	/**
	 * 工号
	 */
	public M setJobNumber(java.lang.String jobNumber) {
		set("job_number", jobNumber);
		return (M)this;
	}
	
	/**
	 * 工号
	 */
	public java.lang.String getJobNumber() {
		return getStr("job_number");
	}

	/**
	 * 排名
	 */
	public M setRankDegree(java.lang.String rankDegree) {
		set("rank_degree", rankDegree);
		return (M)this;
	}
	
	/**
	 * 排名
	 */
	public java.lang.String getRankDegree() {
		return getStr("rank_degree");
	}

	/**
	 * 激励金额
	 */
	public M setAmout(java.lang.Integer amout) {
		set("amout", amout);
		return (M)this;
	}
	
	/**
	 * 激励金额
	 */
	public java.lang.Integer getAmout() {
		return getInt("amout");
	}

	/**
	 * 激励月份
	 */
	public M setAwardMonth(java.util.Date awardMonth) {
		set("award_month", awardMonth);
		return (M)this;
	}
	
	/**
	 * 激励月份
	 */
	public java.util.Date getAwardMonth() {
		return get("award_month");
	}

	/**
	 * 激励原因
	 */
	public M setReason(java.lang.String reason) {
		set("reason", reason);
		return (M)this;
	}
	
	/**
	 * 激励原因
	 */
	public java.lang.String getReason() {
		return getStr("reason");
	}

	/**
	 * 激励日期
	 */
	public M setDateTime(java.util.Date dateTime) {
		set("date_time", dateTime);
		return (M)this;
	}
	
	/**
	 * 激励日期
	 */
	public java.util.Date getDateTime() {
		return get("date_time");
	}

}
