package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseValveInventory<M extends BaseValveInventory<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 二维码
	 */
	public M setQrCode(java.lang.String qrCode) {
		set("qr_code", qrCode);
		return (M)this;
	}
	
	/**
	 * 二维码
	 */
	public java.lang.String getQrCode() {
		return getStr("qr_code");
	}

	/**
	 * 零件编号
	 */
	public M setPartNo(java.lang.String partNo) {
		set("part_no", partNo);
		return (M)this;
	}
	
	/**
	 * 零件编号
	 */
	public java.lang.String getPartNo() {
		return getStr("part_no");
	}

	/**
	 * 零件名称
	 */
	public M setPartName(java.lang.String partName) {
		set("part_name", partName);
		return (M)this;
	}
	
	/**
	 * 零件名称
	 */
	public java.lang.String getPartName() {
		return getStr("part_name");
	}

	/**
	 * 入库数量
	 */
	public M setEntryQty(java.lang.Integer entryQty) {
		set("entry_qty", entryQty);
		return (M)this;
	}
	
	/**
	 * 入库数量
	 */
	public java.lang.Integer getEntryQty() {
		return getInt("entry_qty");
	}

	/**
	 * 出库数量
	 */
	public M setDeliveryQty(java.lang.Integer deliveryQty) {
		set("delivery_qty", deliveryQty);
		return (M)this;
	}
	
	/**
	 * 出库数量
	 */
	public java.lang.Integer getDeliveryQty() {
		return getInt("delivery_qty");
	}

	/**
	 * 对接人
	 */
	public M setOperator(java.lang.String operator) {
		set("operator", operator);
		return (M)this;
	}
	
	/**
	 * 对接人
	 */
	public java.lang.String getOperator() {
		return getStr("operator");
	}

	/**
	 * 备注
	 */
	public M setNote(java.lang.String note) {
		set("note", note);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

	/**
	 * 处理时间
	 */
	public M setDateTime(java.util.Date dateTime) {
		set("date_time", dateTime);
		return (M)this;
	}
	
	/**
	 * 处理时间
	 */
	public java.util.Date getDateTime() {
		return get("date_time");
	}

}
