package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BasePpQrProblem<M extends BasePpQrProblem<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 编号
	 */
	public M setNo(java.lang.String no) {
		set("no", no);
		return (M)this;
	}
	
	/**
	 * 编号
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}

	/**
	 * 问题描述
	 */
	public M setDescription(java.lang.String description) {
		set("description", description);
		return (M)this;
	}
	
	/**
	 * 问题描述
	 */
	public java.lang.String getDescription() {
		return getStr("description");
	}

	/**
	 * 车间
	 */
	public M setWorkshop(java.lang.String workshop) {
		set("workshop", workshop);
		return (M)this;
	}
	
	/**
	 * 车间
	 */
	public java.lang.String getWorkshop() {
		return getStr("workshop");
	}

	/**
	 * 产线
	 */
	public M setProductLine(java.lang.String productLine) {
		set("product_line", productLine);
		return (M)this;
	}
	
	/**
	 * 产线
	 */
	public java.lang.String getProductLine() {
		return getStr("product_line");
	}

	/**
	 * 班次
	 */
	public M setClasses(java.lang.String classes) {
		set("classes", classes);
		return (M)this;
	}
	
	/**
	 * 班次
	 */
	public java.lang.String getClasses() {
		return getStr("classes");
	}

	/**
	 * 是否重复发生
	 */
	public M setIsRepeat(java.lang.Integer isRepeat) {
		set("is_repeat", isRepeat);
		return (M)this;
	}
	
	/**
	 * 是否重复发生
	 */
	public java.lang.Integer getIsRepeat() {
		return getInt("is_repeat");
	}

	/**
	 * 上次发生日期
	 */
	public M setLastHappenDate(java.util.Date lastHappenDate) {
		set("last_happen_date", lastHappenDate);
		return (M)this;
	}
	
	/**
	 * 上次发生日期
	 */
	public java.util.Date getLastHappenDate() {
		return get("last_happen_date");
	}

	/**
	 * 发生问题
	 */
	public M setLastDescription(java.lang.String lastDescription) {
		set("last_description", lastDescription);
		return (M)this;
	}
	
	/**
	 * 发生问题
	 */
	public java.lang.String getLastDescription() {
		return getStr("last_description");
	}

	/**
	 * 问题维度
	 */
	public M setDimensionality(java.lang.String dimensionality) {
		set("dimensionality", dimensionality);
		return (M)this;
	}
	
	/**
	 * 问题维度
	 */
	public java.lang.String getDimensionality() {
		return getStr("dimensionality");
	}

	/**
	 * 主持人ID
	 */
	public M setPersonLeaderId(java.lang.String personLeaderId) {
		set("person_leader_id", personLeaderId);
		return (M)this;
	}
	
	/**
	 * 主持人ID
	 */
	public java.lang.String getPersonLeaderId() {
		return getStr("person_leader_id");
	}

	/**
	 * 主持人姓名
	 */
	public M setPersonLeaderName(java.lang.String personLeaderName) {
		set("person_leader_name", personLeaderName);
		return (M)this;
	}
	
	/**
	 * 主持人姓名
	 */
	public java.lang.String getPersonLeaderName() {
		return getStr("person_leader_name");
	}

	/**
	 * 责任人ID
	 */
	public M setPersonLiableId(java.lang.String personLiableId) {
		set("person_liable_id", personLiableId);
		return (M)this;
	}
	
	/**
	 * 责任人ID
	 */
	public java.lang.String getPersonLiableId() {
		return getStr("person_liable_id");
	}

	/**
	 * 责任人姓名
	 */
	public M setPersonLiableName(java.lang.String personLiableName) {
		set("person_liable_name", personLiableName);
		return (M)this;
	}
	
	/**
	 * 责任人姓名
	 */
	public java.lang.String getPersonLiableName() {
		return getStr("person_liable_name");
	}

	/**
	 * 跟踪人ID
	 */
	public M setPersonTrackingId(java.lang.String personTrackingId) {
		set("person_tracking_id", personTrackingId);
		return (M)this;
	}
	
	/**
	 * 跟踪人ID
	 */
	public java.lang.String getPersonTrackingId() {
		return getStr("person_tracking_id");
	}

	/**
	 * 跟踪人姓名
	 */
	public M setPersonTrackingName(java.lang.String personTrackingName) {
		set("person_tracking_name", personTrackingName);
		return (M)this;
	}
	
	/**
	 * 跟踪人姓名
	 */
	public java.lang.String getPersonTrackingName() {
		return getStr("person_tracking_name");
	}

	/**
	 * 是否升级
	 */
	public M setIsUpgrade(java.lang.Integer isUpgrade) {
		set("is_upgrade", isUpgrade);
		return (M)this;
	}
	
	/**
	 * 是否升级
	 */
	public java.lang.Integer getIsUpgrade() {
		return getInt("is_upgrade");
	}

	/**
	 * 下次回顾日期
	 */
	public M setNextReviewDate(java.util.Date nextReviewDate) {
		set("next_review_date", nextReviewDate);
		return (M)this;
	}
	
	/**
	 * 下次回顾日期
	 */
	public java.util.Date getNextReviewDate() {
		return get("next_review_date");
	}

	/**
	 * 问题第一发现人ID
	 */
	public M setFindUserid(java.lang.String findUserid) {
		set("find_userid", findUserid);
		return (M)this;
	}
	
	/**
	 * 问题第一发现人ID
	 */
	public java.lang.String getFindUserid() {
		return getStr("find_userid");
	}

	/**
	 * 问题第一发现人姓名
	 */
	public M setFindUsername(java.lang.String findUsername) {
		set("find_username", findUsername);
		return (M)this;
	}
	
	/**
	 * 问题第一发现人姓名
	 */
	public java.lang.String getFindUsername() {
		return getStr("find_username");
	}

	/**
	 * 问题第一发现人部门ID
	 */
	public M setFindUserPartId(java.lang.String findUserPartId) {
		set("find_user_part_id", findUserPartId);
		return (M)this;
	}
	
	/**
	 * 问题第一发现人部门ID
	 */
	public java.lang.String getFindUserPartId() {
		return getStr("find_user_part_id");
	}

	/**
	 * 问题第一发现人部门名称
	 */
	public M setFindUserPartName(java.lang.String findUserPartName) {
		set("find_user_part_name", findUserPartName);
		return (M)this;
	}
	
	/**
	 * 问题第一发现人部门名称
	 */
	public java.lang.String getFindUserPartName() {
		return getStr("find_user_part_name");
	}

	/**
	 * 拍照上传图片
	 */
	public M setFilename(java.lang.String filename) {
		set("filename", filename);
		return (M)this;
	}
	
	/**
	 * 拍照上传图片
	 */
	public java.lang.String getFilename() {
		return getStr("filename");
	}

	/**
	 * 发生日期
	 */
	public M setHappenDate(java.util.Date happenDate) {
		set("happen_date", happenDate);
		return (M)this;
	}
	
	/**
	 * 发生日期
	 */
	public java.util.Date getHappenDate() {
		return get("happen_date");
	}

	/**
	 * when
	 */
	public M setWhen(java.lang.String when) {
		set("when", when);
		return (M)this;
	}
	
	/**
	 * when
	 */
	public java.lang.String getWhen() {
		return getStr("when");
	}

	/**
	 * who
	 */
	public M setWho(java.lang.String who) {
		set("who", who);
		return (M)this;
	}
	
	/**
	 * who
	 */
	public java.lang.String getWho() {
		return getStr("who");
	}

	/**
	 * where
	 */
	public M setWhere(java.lang.String where) {
		set("where", where);
		return (M)this;
	}
	
	/**
	 * where
	 */
	public java.lang.String getWhere() {
		return getStr("where");
	}

	/**
	 * what
	 */
	public M setWhat(java.lang.String what) {
		set("what", what);
		return (M)this;
	}
	
	/**
	 * what
	 */
	public java.lang.String getWhat() {
		return getStr("what");
	}

	/**
	 * why
	 */
	public M setWhy(java.lang.String why) {
		set("why", why);
		return (M)this;
	}
	
	/**
	 * why
	 */
	public java.lang.String getWhy() {
		return getStr("why");
	}

	/**
	 * how
	 */
	public M setHow(java.lang.String how) {
		set("how", how);
		return (M)this;
	}
	
	/**
	 * how
	 */
	public java.lang.String getHow() {
		return getStr("how");
	}

	/**
	 * how_match
	 */
	public M setHowMatch(java.lang.String howMatch) {
		set("how_match", howMatch);
		return (M)this;
	}
	
	/**
	 * how_match
	 */
	public java.lang.String getHowMatch() {
		return getStr("how_match");
	}

	/**
	 * 影响
	 */
	public M setEffect(java.lang.String effect) {
		set("effect", effect);
		return (M)this;
	}
	
	/**
	 * 影响
	 */
	public java.lang.String getEffect() {
		return getStr("effect");
	}

	/**
	 * 遏制状态:0=否,1=是,2=完成
	 */
	public M setContainStatu(java.lang.Integer containStatu) {
		set("contain_statu", containStatu);
		return (M)this;
	}
	
	/**
	 * 遏制状态:0=否,1=是,2=完成
	 */
	public java.lang.Integer getContainStatu() {
		return getInt("contain_statu");
	}

	/**
	 * 来料状态:0=否,1=是
	 */
	public M setContainLlStatu(java.lang.Integer containLlStatu) {
		set("contain_ll_statu", containLlStatu);
		return (M)this;
	}
	
	/**
	 * 来料状态:0=否,1=是
	 */
	public java.lang.Integer getContainLlStatu() {
		return getInt("contain_ll_statu");
	}

	/**
	 * 来料数量/范围
	 */
	public M setContainLlQty(java.lang.String containLlQty) {
		set("contain_ll_qty", containLlQty);
		return (M)this;
	}
	
	/**
	 * 来料数量/范围
	 */
	public java.lang.String getContainLlQty() {
		return getStr("contain_ll_qty");
	}

	/**
	 * 来料NG数量
	 */
	public M setContainLlNgQty(java.lang.String containLlNgQty) {
		set("contain_ll_ng_qty", containLlNgQty);
		return (M)this;
	}
	
	/**
	 * 来料NG数量
	 */
	public java.lang.String getContainLlNgQty() {
		return getStr("contain_ll_ng_qty");
	}

	/**
	 * 来料措施
	 */
	public M setContainLlMeasure(java.lang.String containLlMeasure) {
		set("contain_ll_measure", containLlMeasure);
		return (M)this;
	}
	
	/**
	 * 来料措施
	 */
	public java.lang.String getContainLlMeasure() {
		return getStr("contain_ll_measure");
	}

	/**
	 * 在制品状态:0=否,1=是
	 */
	public M setContainZzpStatu(java.lang.Integer containZzpStatu) {
		set("contain_zzp_statu", containZzpStatu);
		return (M)this;
	}
	
	/**
	 * 在制品状态:0=否,1=是
	 */
	public java.lang.Integer getContainZzpStatu() {
		return getInt("contain_zzp_statu");
	}

	/**
	 * 在制品数量/范围
	 */
	public M setContainZzpQty(java.lang.String containZzpQty) {
		set("contain_zzp_qty", containZzpQty);
		return (M)this;
	}
	
	/**
	 * 在制品数量/范围
	 */
	public java.lang.String getContainZzpQty() {
		return getStr("contain_zzp_qty");
	}

	/**
	 * 在制品NG数量
	 */
	public M setContainZzpNgQty(java.lang.String containZzpNgQty) {
		set("contain_zzp_ng_qty", containZzpNgQty);
		return (M)this;
	}
	
	/**
	 * 在制品NG数量
	 */
	public java.lang.String getContainZzpNgQty() {
		return getStr("contain_zzp_ng_qty");
	}

	/**
	 * 在制品措施
	 */
	public M setContainZzpMeasure(java.lang.String containZzpMeasure) {
		set("contain_zzp_measure", containZzpMeasure);
		return (M)this;
	}
	
	/**
	 * 在制品措施
	 */
	public java.lang.String getContainZzpMeasure() {
		return getStr("contain_zzp_measure");
	}

	/**
	 * 成品状态:0=否,1=是
	 */
	public M setContainCpStatu(java.lang.Integer containCpStatu) {
		set("contain_cp_statu", containCpStatu);
		return (M)this;
	}
	
	/**
	 * 成品状态:0=否,1=是
	 */
	public java.lang.Integer getContainCpStatu() {
		return getInt("contain_cp_statu");
	}

	/**
	 * 成品数量/范围
	 */
	public M setContainCpQty(java.lang.String containCpQty) {
		set("contain_cp_qty", containCpQty);
		return (M)this;
	}
	
	/**
	 * 成品数量/范围
	 */
	public java.lang.String getContainCpQty() {
		return getStr("contain_cp_qty");
	}

	/**
	 * 成品NG数量
	 */
	public M setContainCpNgQty(java.lang.String containCpNgQty) {
		set("contain_cp_ng_qty", containCpNgQty);
		return (M)this;
	}
	
	/**
	 * 成品NG数量
	 */
	public java.lang.String getContainCpNgQty() {
		return getStr("contain_cp_ng_qty");
	}

	/**
	 * 成品措施
	 */
	public M setContainCpMeasure(java.lang.String containCpMeasure) {
		set("contain_cp_measure", containCpMeasure);
		return (M)this;
	}
	
	/**
	 * 成品措施
	 */
	public java.lang.String getContainCpMeasure() {
		return getStr("contain_cp_measure");
	}

	/**
	 * 客户处状态:0=否,1=是
	 */
	public M setContainKhcStatu(java.lang.Integer containKhcStatu) {
		set("contain_khc_statu", containKhcStatu);
		return (M)this;
	}
	
	/**
	 * 客户处状态:0=否,1=是
	 */
	public java.lang.Integer getContainKhcStatu() {
		return getInt("contain_khc_statu");
	}

	/**
	 * 客户处数量/范围
	 */
	public M setContainKhcQty(java.lang.String containKhcQty) {
		set("contain_khc_qty", containKhcQty);
		return (M)this;
	}
	
	/**
	 * 客户处数量/范围
	 */
	public java.lang.String getContainKhcQty() {
		return getStr("contain_khc_qty");
	}

	/**
	 * 客户处NG数量
	 */
	public M setContainKhcNgQty(java.lang.String containKhcNgQty) {
		set("contain_khc_ng_qty", containKhcNgQty);
		return (M)this;
	}
	
	/**
	 * 客户处NG数量
	 */
	public java.lang.String getContainKhcNgQty() {
		return getStr("contain_khc_ng_qty");
	}

	/**
	 * 客户处措施
	 */
	public M setContainKhcMeasure(java.lang.String containKhcMeasure) {
		set("contain_khc_measure", containKhcMeasure);
		return (M)this;
	}
	
	/**
	 * 客户处措施
	 */
	public java.lang.String getContainKhcMeasure() {
		return getStr("contain_khc_measure");
	}

	/**
	 * 临时措施
	 */
	public M setContainTemp(java.lang.String containTemp) {
		set("contain_temp", containTemp);
		return (M)this;
	}
	
	/**
	 * 临时措施
	 */
	public java.lang.String getContainTemp() {
		return getStr("contain_temp");
	}

	/**
	 * 遏制表单
	 */
	public M setContainForm(java.lang.String containForm) {
		set("contain_form", containForm);
		return (M)this;
	}
	
	/**
	 * 遏制表单
	 */
	public java.lang.String getContainForm() {
		return getStr("contain_form");
	}

	/**
	 * 追溯
	 */
	public M setRetrospect(java.lang.String retrospect) {
		set("retrospect", retrospect);
		return (M)this;
	}
	
	/**
	 * 追溯
	 */
	public java.lang.String getRetrospect() {
		return getStr("retrospect");
	}

	/**
	 * 遏制状态颜色
	 */
	public M setContainStatuColor(java.lang.Boolean containStatuColor) {
		set("contain_statu_color", containStatuColor);
		return (M)this;
	}
	
	/**
	 * 遏制状态颜色
	 */
	public java.lang.Boolean getContainStatuColor() {
		return getBoolean("contain_statu_color");
	}

	/**
	 * 人
	 */
	public M setReasonPeople(java.lang.String reasonPeople) {
		set("reason_people", reasonPeople);
		return (M)this;
	}
	
	/**
	 * 人
	 */
	public java.lang.String getReasonPeople() {
		return getStr("reason_people");
	}

	/**
	 * 机
	 */
	public M setReasonEquipment(java.lang.String reasonEquipment) {
		set("reason_equipment", reasonEquipment);
		return (M)this;
	}
	
	/**
	 * 机
	 */
	public java.lang.String getReasonEquipment() {
		return getStr("reason_equipment");
	}

	/**
	 * 料
	 */
	public M setReasonMaterial(java.lang.String reasonMaterial) {
		set("reason_material", reasonMaterial);
		return (M)this;
	}
	
	/**
	 * 料
	 */
	public java.lang.String getReasonMaterial() {
		return getStr("reason_material");
	}

	/**
	 * 法
	 */
	public M setReasonFa(java.lang.String reasonFa) {
		set("reason_fa", reasonFa);
		return (M)this;
	}
	
	/**
	 * 法
	 */
	public java.lang.String getReasonFa() {
		return getStr("reason_fa");
	}

	/**
	 * 环
	 */
	public M setReasonEnvironment(java.lang.String reasonEnvironment) {
		set("reason_environment", reasonEnvironment);
		return (M)this;
	}
	
	/**
	 * 环
	 */
	public java.lang.String getReasonEnvironment() {
		return getStr("reason_environment");
	}

	/**
	 * 测
	 */
	public M setReasonMeasure(java.lang.String reasonMeasure) {
		set("reason_measure", reasonMeasure);
		return (M)this;
	}
	
	/**
	 * 测
	 */
	public java.lang.String getReasonMeasure() {
		return getStr("reason_measure");
	}

	/**
	 * 产生原因：技术
	 */
	public M setProduceReasonSkill(java.lang.String produceReasonSkill) {
		set("produce_reason_skill", produceReasonSkill);
		return (M)this;
	}
	
	/**
	 * 产生原因：技术
	 */
	public java.lang.String getProduceReasonSkill() {
		return getStr("produce_reason_skill");
	}

	/**
	 * 产生原因：技术有效性
	 */
	public M setProduceResaonSkillValidity(java.lang.String produceResaonSkillValidity) {
		set("produce_resaon_skill_validity", produceResaonSkillValidity);
		return (M)this;
	}
	
	/**
	 * 产生原因：技术有效性
	 */
	public java.lang.String getProduceResaonSkillValidity() {
		return getStr("produce_resaon_skill_validity");
	}

	/**
	 * 产生原因：管理
	 */
	public M setProduceReasonManage(java.lang.String produceReasonManage) {
		set("produce_reason_manage", produceReasonManage);
		return (M)this;
	}
	
	/**
	 * 产生原因：管理
	 */
	public java.lang.String getProduceReasonManage() {
		return getStr("produce_reason_manage");
	}

	/**
	 * 产生原因：管理有效性
	 */
	public M setProduceResaonManageValidity(java.lang.String produceResaonManageValidity) {
		set("produce_resaon_manage_validity", produceResaonManageValidity);
		return (M)this;
	}
	
	/**
	 * 产生原因：管理有效性
	 */
	public java.lang.String getProduceResaonManageValidity() {
		return getStr("produce_resaon_manage_validity");
	}

	/**
	 * 流出原因：技术
	 */
	public M setOutflowReasonSkill(java.lang.String outflowReasonSkill) {
		set("outflow_reason_skill", outflowReasonSkill);
		return (M)this;
	}
	
	/**
	 * 流出原因：技术
	 */
	public java.lang.String getOutflowReasonSkill() {
		return getStr("outflow_reason_skill");
	}

	/**
	 * 流出原因：技术有效性
	 */
	public M setOutflowResaonSkillValidity(java.lang.String outflowResaonSkillValidity) {
		set("outflow_resaon_skill_validity", outflowResaonSkillValidity);
		return (M)this;
	}
	
	/**
	 * 流出原因：技术有效性
	 */
	public java.lang.String getOutflowResaonSkillValidity() {
		return getStr("outflow_resaon_skill_validity");
	}

	/**
	 * 流出原因：管理
	 */
	public M setOutflowReasonManage(java.lang.String outflowReasonManage) {
		set("outflow_reason_manage", outflowReasonManage);
		return (M)this;
	}
	
	/**
	 * 流出原因：管理
	 */
	public java.lang.String getOutflowReasonManage() {
		return getStr("outflow_reason_manage");
	}

	/**
	 * 流出原因：管理有效性
	 */
	public M setOutflowResaonManageValidity(java.lang.String outflowResaonManageValidity) {
		set("outflow_resaon_manage_validity", outflowResaonManageValidity);
		return (M)this;
	}
	
	/**
	 * 流出原因：管理有效性
	 */
	public java.lang.String getOutflowResaonManageValidity() {
		return getStr("outflow_resaon_manage_validity");
	}

	/**
	 * 原因分析附件
	 */
	public M setReasonFile(java.lang.String reasonFile) {
		set("reason_file", reasonFile);
		return (M)this;
	}
	
	/**
	 * 原因分析附件
	 */
	public java.lang.String getReasonFile() {
		return getStr("reason_file");
	}

	/**
	 * 原因分析确认人
	 */
	public M setReasonConfirmUser(java.lang.String reasonConfirmUser) {
		set("reason_confirm_user", reasonConfirmUser);
		return (M)this;
	}
	
	/**
	 * 原因分析确认人
	 */
	public java.lang.String getReasonConfirmUser() {
		return getStr("reason_confirm_user");
	}

	/**
	 * 原因分析确认时间
	 */
	public M setReasonConfirmDate(java.util.Date reasonConfirmDate) {
		set("reason_confirm_date", reasonConfirmDate);
		return (M)this;
	}
	
	/**
	 * 原因分析确认时间
	 */
	public java.util.Date getReasonConfirmDate() {
		return get("reason_confirm_date");
	}

	/**
	 * 原因分析状态颜色
	 */
	public M setReasonStatuColor(java.lang.Boolean reasonStatuColor) {
		set("reason_statu_color", reasonStatuColor);
		return (M)this;
	}
	
	/**
	 * 原因分析状态颜色
	 */
	public java.lang.Boolean getReasonStatuColor() {
		return getBoolean("reason_statu_color");
	}

	/**
	 * 永久措施：防产生-技术-行动计划
	 */
	public M setMeasurePgSkillPlan(java.lang.String measurePgSkillPlan) {
		set("measure_pg_skill_plan", measurePgSkillPlan);
		return (M)this;
	}
	
	/**
	 * 永久措施：防产生-技术-行动计划
	 */
	public java.lang.String getMeasurePgSkillPlan() {
		return getStr("measure_pg_skill_plan");
	}

	/**
	 * 永久措施：防产生-技术-责任人ID
	 */
	public M setMeasurePgSkillUserid(java.lang.String measurePgSkillUserid) {
		set("measure_pg_skill_userid", measurePgSkillUserid);
		return (M)this;
	}
	
	/**
	 * 永久措施：防产生-技术-责任人ID
	 */
	public java.lang.String getMeasurePgSkillUserid() {
		return getStr("measure_pg_skill_userid");
	}

	/**
	 * 永久措施：防产生-技术-责任人姓名
	 */
	public M setMeasurePgSkillUsername(java.lang.String measurePgSkillUsername) {
		set("measure_pg_skill_username", measurePgSkillUsername);
		return (M)this;
	}
	
	/**
	 * 永久措施：防产生-技术-责任人姓名
	 */
	public java.lang.String getMeasurePgSkillUsername() {
		return getStr("measure_pg_skill_username");
	}

	/**
	 * 永久措施：防产生-技术-完成时间
	 */
	public M setMeasurePgSkillDate(java.util.Date measurePgSkillDate) {
		set("measure_pg_skill_date", measurePgSkillDate);
		return (M)this;
	}
	
	/**
	 * 永久措施：防产生-技术-完成时间
	 */
	public java.util.Date getMeasurePgSkillDate() {
		return get("measure_pg_skill_date");
	}

	/**
	 * 永久措施：防产生-管理-行动计划
	 */
	public M setMeasurePgManagePlan(java.lang.String measurePgManagePlan) {
		set("measure_pg_manage_plan", measurePgManagePlan);
		return (M)this;
	}
	
	/**
	 * 永久措施：防产生-管理-行动计划
	 */
	public java.lang.String getMeasurePgManagePlan() {
		return getStr("measure_pg_manage_plan");
	}

	/**
	 * 永久措施：防产生-管理-责任人ID
	 */
	public M setMeasurePgManageUserid(java.lang.String measurePgManageUserid) {
		set("measure_pg_manage_userid", measurePgManageUserid);
		return (M)this;
	}
	
	/**
	 * 永久措施：防产生-管理-责任人ID
	 */
	public java.lang.String getMeasurePgManageUserid() {
		return getStr("measure_pg_manage_userid");
	}

	/**
	 * 永久措施：防产生-管理-责任人姓名
	 */
	public M setMeasurePgManageUsername(java.lang.String measurePgManageUsername) {
		set("measure_pg_manage_username", measurePgManageUsername);
		return (M)this;
	}
	
	/**
	 * 永久措施：防产生-管理-责任人姓名
	 */
	public java.lang.String getMeasurePgManageUsername() {
		return getStr("measure_pg_manage_username");
	}

	/**
	 * 永久措施：防产生-管理-完成时间
	 */
	public M setMeasurePgManageDate(java.util.Date measurePgManageDate) {
		set("measure_pg_manage_date", measurePgManageDate);
		return (M)this;
	}
	
	/**
	 * 永久措施：防产生-管理-完成时间
	 */
	public java.util.Date getMeasurePgManageDate() {
		return get("measure_pg_manage_date");
	}

	/**
	 * 永久措施：防流出-技术-行动计划
	 */
	public M setMeasurePoSkillPlan(java.lang.String measurePoSkillPlan) {
		set("measure_po_skill_plan", measurePoSkillPlan);
		return (M)this;
	}
	
	/**
	 * 永久措施：防流出-技术-行动计划
	 */
	public java.lang.String getMeasurePoSkillPlan() {
		return getStr("measure_po_skill_plan");
	}

	/**
	 * 永久措施：防流出-技术-责任人ID
	 */
	public M setMeasurePoSkillUserid(java.lang.String measurePoSkillUserid) {
		set("measure_po_skill_userid", measurePoSkillUserid);
		return (M)this;
	}
	
	/**
	 * 永久措施：防流出-技术-责任人ID
	 */
	public java.lang.String getMeasurePoSkillUserid() {
		return getStr("measure_po_skill_userid");
	}

	/**
	 * 永久措施：防流出-技术-责任人姓名
	 */
	public M setMeasurePoSkillUsername(java.lang.String measurePoSkillUsername) {
		set("measure_po_skill_username", measurePoSkillUsername);
		return (M)this;
	}
	
	/**
	 * 永久措施：防流出-技术-责任人姓名
	 */
	public java.lang.String getMeasurePoSkillUsername() {
		return getStr("measure_po_skill_username");
	}

	/**
	 * 永久措施：防流出-技术-完成时间
	 */
	public M setMeasurePoSkillDate(java.util.Date measurePoSkillDate) {
		set("measure_po_skill_date", measurePoSkillDate);
		return (M)this;
	}
	
	/**
	 * 永久措施：防流出-技术-完成时间
	 */
	public java.util.Date getMeasurePoSkillDate() {
		return get("measure_po_skill_date");
	}

	/**
	 * 永久措施：防流出-管理-行动计划
	 */
	public M setMeasurePoManagePlan(java.lang.String measurePoManagePlan) {
		set("measure_po_manage_plan", measurePoManagePlan);
		return (M)this;
	}
	
	/**
	 * 永久措施：防流出-管理-行动计划
	 */
	public java.lang.String getMeasurePoManagePlan() {
		return getStr("measure_po_manage_plan");
	}

	/**
	 * 永久措施：防流出-管理-责任人ID
	 */
	public M setMeasurePoManageUserid(java.lang.String measurePoManageUserid) {
		set("measure_po_manage_userid", measurePoManageUserid);
		return (M)this;
	}
	
	/**
	 * 永久措施：防流出-管理-责任人ID
	 */
	public java.lang.String getMeasurePoManageUserid() {
		return getStr("measure_po_manage_userid");
	}

	/**
	 * 永久措施：防流出-管理-责任人姓名
	 */
	public M setMeasurePoManageUsername(java.lang.String measurePoManageUsername) {
		set("measure_po_manage_username", measurePoManageUsername);
		return (M)this;
	}
	
	/**
	 * 永久措施：防流出-管理-责任人姓名
	 */
	public java.lang.String getMeasurePoManageUsername() {
		return getStr("measure_po_manage_username");
	}

	/**
	 * 永久措施：防流出-管理-完成时间
	 */
	public M setMeasurePoManageDate(java.util.Date measurePoManageDate) {
		set("measure_po_manage_date", measurePoManageDate);
		return (M)this;
	}
	
	/**
	 * 永久措施：防流出-管理-完成时间
	 */
	public java.util.Date getMeasurePoManageDate() {
		return get("measure_po_manage_date");
	}

	/**
	 * 永久措施：附件
	 */
	public M setMeasureFile(java.lang.String measureFile) {
		set("measure_file", measureFile);
		return (M)this;
	}
	
	/**
	 * 永久措施：附件
	 */
	public java.lang.String getMeasureFile() {
		return getStr("measure_file");
	}

	/**
	 * 永久措施：跟踪情况
	 */
	public M setMeasureTracking(java.lang.String measureTracking) {
		set("measure_tracking", measureTracking);
		return (M)this;
	}
	
	/**
	 * 永久措施：跟踪情况
	 */
	public java.lang.String getMeasureTracking() {
		return getStr("measure_tracking");
	}

	/**
	 * 永久措施：状态颜色
	 */
	public M setMeasureStatu(java.lang.Boolean measureStatu) {
		set("measure_statu", measureStatu);
		return (M)this;
	}
	
	/**
	 * 永久措施：状态颜色
	 */
	public java.lang.Boolean getMeasureStatu() {
		return getBoolean("measure_statu");
	}

	/**
	 * 标准化：FMEA
	 */
	public M setStandardFmea(java.lang.Integer standardFmea) {
		set("standard_fmea", standardFmea);
		return (M)this;
	}
	
	/**
	 * 标准化：FMEA
	 */
	public java.lang.Integer getStandardFmea() {
		return getInt("standard_fmea");
	}

	/**
	 * 标准化：FMEA文件
	 */
	public M setStandardFmeaFile(java.lang.String standardFmeaFile) {
		set("standard_fmea_file", standardFmeaFile);
		return (M)this;
	}
	
	/**
	 * 标准化：FMEA文件
	 */
	public java.lang.String getStandardFmeaFile() {
		return getStr("standard_fmea_file");
	}

	/**
	 * 标准化：CP
	 */
	public M setStandardCp(java.lang.Integer standardCp) {
		set("standard_cp", standardCp);
		return (M)this;
	}
	
	/**
	 * 标准化：CP
	 */
	public java.lang.Integer getStandardCp() {
		return getInt("standard_cp");
	}

	/**
	 * 标准化：CP文件
	 */
	public M setStandardCpFile(java.lang.String standardCpFile) {
		set("standard_cp_file", standardCpFile);
		return (M)this;
	}
	
	/**
	 * 标准化：CP文件
	 */
	public java.lang.String getStandardCpFile() {
		return getStr("standard_cp_file");
	}

	/**
	 * 标准化：作业指导书
	 */
	public M setStandardZyzds(java.lang.Integer standardZyzds) {
		set("standard_zyzds", standardZyzds);
		return (M)this;
	}
	
	/**
	 * 标准化：作业指导书
	 */
	public java.lang.Integer getStandardZyzds() {
		return getInt("standard_zyzds");
	}

	/**
	 * 标准化：作业指导书文件
	 */
	public M setStandardZyzdsFile(java.lang.String standardZyzdsFile) {
		set("standard_zyzds_file", standardZyzdsFile);
		return (M)this;
	}
	
	/**
	 * 标准化：作业指导书文件
	 */
	public java.lang.String getStandardZyzdsFile() {
		return getStr("standard_zyzds_file");
	}

	/**
	 * 标准化：横向展开
	 */
	public M setStandardHxzk(java.lang.Integer standardHxzk) {
		set("standard_hxzk", standardHxzk);
		return (M)this;
	}
	
	/**
	 * 标准化：横向展开
	 */
	public java.lang.Integer getStandardHxzk() {
		return getInt("standard_hxzk");
	}

	/**
	 * 标准化：横向展开文件
	 */
	public M setStandardHxzkFile(java.lang.String standardHxzkFile) {
		set("standard_hxzk_file", standardHxzkFile);
		return (M)this;
	}
	
	/**
	 * 标准化：横向展开文件
	 */
	public java.lang.String getStandardHxzkFile() {
		return getStr("standard_hxzk_file");
	}

	/**
	 * 点检表附件
	 */
	public M setDjbUrl(java.lang.String djbUrl) {
		set("djb_url", djbUrl);
		return (M)this;
	}
	
	/**
	 * 点检表附件
	 */
	public java.lang.String getDjbUrl() {
		return getStr("djb_url");
	}

	/**
	 * 检验指导书附件
	 */
	public M setJyzdsUrl(java.lang.String jyzdsUrl) {
		set("jyzds_url", jyzdsUrl);
		return (M)this;
	}
	
	/**
	 * 检验指导书附件
	 */
	public java.lang.String getJyzdsUrl() {
		return getStr("jyzds_url");
	}

	/**
	 * 分层审核附件
	 */
	public M setFcshUrl(java.lang.String fcshUrl) {
		set("fcsh_url", fcshUrl);
		return (M)this;
	}
	
	/**
	 * 分层审核附件
	 */
	public java.lang.String getFcshUrl() {
		return getStr("fcsh_url");
	}

	/**
	 * 标准化：状态颜色
	 */
	public M setStandardStatu(java.lang.Boolean standardStatu) {
		set("standard_statu", standardStatu);
		return (M)this;
	}
	
	/**
	 * 标准化：状态颜色
	 */
	public java.lang.Boolean getStandardStatu() {
		return getBoolean("standard_statu");
	}

	/**
	 * 问题状态:0=发起,1=已升版,2=已升级,3=已关闭
	 */
	public M setStatu(java.lang.Integer statu) {
		set("statu", statu);
		return (M)this;
	}
	
	/**
	 * 问题状态:0=发起,1=已升版,2=已升级,3=已关闭
	 */
	public java.lang.Integer getStatu() {
		return getInt("statu");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	/**
	 * 0,记录。1已过升版，记录在统计中
	 */
	public M setIsstatu2(java.lang.Integer isstatu2) {
		set("isstatu2", isstatu2);
		return (M)this;
	}
	
	/**
	 * 0,记录。1已过升版，记录在统计中
	 */
	public java.lang.Integer getIsstatu2() {
		return getInt("isstatu2");
	}

	/**
	 * 1再次升版
	 */
	public M setStatu2(java.lang.Integer statu2) {
		set("statu2", statu2);
		return (M)this;
	}
	
	/**
	 * 1再次升版
	 */
	public java.lang.Integer getStatu2() {
		return getInt("statu2");
	}

	/**
	 * 再再次升版
	 */
	public M setStatu3(java.lang.Integer statu3) {
		set("statu3", statu3);
		return (M)this;
	}
	
	/**
	 * 再再次升版
	 */
	public java.lang.Integer getStatu3() {
		return getInt("statu3");
	}

	/**
	 * 关闭日期
	 */
	public M setCloseDate(java.util.Date closeDate) {
		set("close_date", closeDate);
		return (M)this;
	}
	
	/**
	 * 关闭日期
	 */
	public java.util.Date getCloseDate() {
		return get("close_date");
	}

	/**
	 * 生产姓名
	 */
	public M setScUsernames(java.lang.String scUsernames) {
		set("sc_usernames", scUsernames);
		return (M)this;
	}
	
	/**
	 * 生产姓名
	 */
	public java.lang.String getScUsernames() {
		return getStr("sc_usernames");
	}

	/**
	 * 技术姓名
	 */
	public M setJsUsernames(java.lang.String jsUsernames) {
		set("js_usernames", jsUsernames);
		return (M)this;
	}
	
	/**
	 * 技术姓名
	 */
	public java.lang.String getJsUsernames() {
		return getStr("js_usernames");
	}

	/**
	 * 质量人姓名
	 */
	public M setZlUsernames(java.lang.String zlUsernames) {
		set("zl_usernames", zlUsernames);
		return (M)this;
	}
	
	/**
	 * 质量人姓名
	 */
	public java.lang.String getZlUsernames() {
		return getStr("zl_usernames");
	}

	/**
	 * 主持人备忘录
	 */
	public M setZhuchirenbwl(java.lang.String zhuchirenbwl) {
		set("zhuchirenbwl", zhuchirenbwl);
		return (M)this;
	}
	
	/**
	 * 主持人备忘录
	 */
	public java.lang.String getZhuchirenbwl() {
		return getStr("zhuchirenbwl");
	}

	/**
	 * 问题输出要求
	 */
	public M setWtscyq(java.lang.String wtscyq) {
		set("wtscyq", wtscyq);
		return (M)this;
	}
	
	/**
	 * 问题输出要求
	 */
	public java.lang.String getWtscyq() {
		return getStr("wtscyq");
	}

	/**
	 * 产品名称
	 */
	public M setCpName(java.lang.String cpName) {
		set("cp_name", cpName);
		return (M)this;
	}
	
	/**
	 * 产品名称
	 */
	public java.lang.String getCpName() {
		return getStr("cp_name");
	}

	/**
	 * 批次
	 */
	public M setPcNo(java.lang.String pcNo) {
		set("pc_no", pcNo);
		return (M)this;
	}
	
	/**
	 * 批次
	 */
	public java.lang.String getPcNo() {
		return getStr("pc_no");
	}

	/**
	 * 供应商问题，默认不是
	 */
	public M setGysNbwt(java.lang.Integer gysNbwt) {
		set("gys_nbwt", gysNbwt);
		return (M)this;
	}
	
	/**
	 * 供应商问题，默认不是
	 */
	public java.lang.Integer getGysNbwt() {
		return getInt("gys_nbwt");
	}

	/**
	 * SQDIP问题ID
	 */
	public M setSqdipId(java.lang.Integer sqdipId) {
		set("sqdip_id", sqdipId);
		return (M)this;
	}
	
	/**
	 * SQDIP问题ID
	 */
	public java.lang.Integer getSqdipId() {
		return getInt("sqdip_id");
	}

	/**
	 * 1隐藏
	 */
	public M setIsHide(java.lang.Integer isHide) {
		set("is_hide", isHide);
		return (M)this;
	}
	
	/**
	 * 1隐藏
	 */
	public java.lang.Integer getIsHide() {
		return getInt("is_hide");
	}

	/**
	 * pp班长id
	 */
	public M setShiftLeaderId(java.lang.String shiftLeaderId) {
		set("shift_leader_id", shiftLeaderId);
		return (M)this;
	}
	
	/**
	 * pp班长id
	 */
	public java.lang.String getShiftLeaderId() {
		return getStr("shift_leader_id");
	}

	/**
	 * pp班长姓名
	 */
	public M setShiftLeaderName(java.lang.String shiftLeaderName) {
		set("shift_leader_name", shiftLeaderName);
		return (M)this;
	}
	
	/**
	 * pp班长姓名
	 */
	public java.lang.String getShiftLeaderName() {
		return getStr("shift_leader_name");
	}

	/**
	 * pp审核结果1=同意，2=拒绝
	 */
	public M setPpcheckResult(java.lang.Integer ppcheckResult) {
		set("ppcheck_result", ppcheckResult);
		return (M)this;
	}
	
	/**
	 * pp审核结果1=同意，2=拒绝
	 */
	public java.lang.Integer getPpcheckResult() {
		return getInt("ppcheck_result");
	}

}
