package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseS6sDistriction<M extends BaseS6sDistriction<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 区域名称
	 */
	public M setDisName(java.lang.String disName) {
		set("dis_name", disName);
		return (M)this;
	}
	
	/**
	 * 区域名称
	 */
	public java.lang.String getDisName() {
		return getStr("dis_name");
	}

	/**
	 * 负责人
	 */
	public M setPrincipal(java.lang.String principal) {
		set("principal", principal);
		return (M)this;
	}
	
	/**
	 * 负责人
	 */
	public java.lang.String getPrincipal() {
		return getStr("principal");
	}

	/**
	 * 员工数量
	 */
	public M setStaffQty(java.lang.Integer staffQty) {
		set("staff_qty", staffQty);
		return (M)this;
	}
	
	/**
	 * 员工数量
	 */
	public java.lang.Integer getStaffQty() {
		return getInt("staff_qty");
	}

	/**
	 * 白手套工程展示顺序
	 */
	public M setGloveSequence(java.lang.Integer gloveSequence) {
		set("glove_sequence", gloveSequence);
		return (M)this;
	}
	
	/**
	 * 白手套工程展示顺序
	 */
	public java.lang.Integer getGloveSequence() {
		return getInt("glove_sequence");
	}

}
