package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseValveParts<M extends BaseValveParts<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 二维码
	 */
	public M setQrCode(java.lang.String qrCode) {
		set("qr_code", qrCode);
		return (M)this;
	}
	
	/**
	 * 二维码
	 */
	public java.lang.String getQrCode() {
		return getStr("qr_code");
	}

	/**
	 * 零件编号
	 */
	public M setPartNo(java.lang.String partNo) {
		set("part_no", partNo);
		return (M)this;
	}
	
	/**
	 * 零件编号
	 */
	public java.lang.String getPartNo() {
		return getStr("part_no");
	}

	/**
	 * 批次号
	 */
	public M setBatchNo(java.lang.String batchNo) {
		set("batch_no", batchNo);
		return (M)this;
	}
	
	/**
	 * 批次号
	 */
	public java.lang.String getBatchNo() {
		return getStr("batch_no");
	}

	/**
	 * 初始数量
	 */
	public M setInitQty(java.lang.Integer initQty) {
		set("init_qty", initQty);
		return (M)this;
	}
	
	/**
	 * 初始数量
	 */
	public java.lang.Integer getInitQty() {
		return getInt("init_qty");
	}

	/**
	 * 零件名称
	 */
	public M setPartName(java.lang.String partName) {
		set("part_name", partName);
		return (M)this;
	}
	
	/**
	 * 零件名称
	 */
	public java.lang.String getPartName() {
		return getStr("part_name");
	}

	/**
	 * 零件类型
	 */
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 零件类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 备注
	 */
	public M setNote(java.lang.String note) {
		set("note", note);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public java.lang.String getNote() {
		return getStr("note");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

}
