package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseYwTest<M extends BaseYwTest<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 车间
	 */
	public M setWorkshop(java.lang.Integer workshop) {
		set("workshop", workshop);
		return (M)this;
	}
	
	/**
	 * 车间
	 */
	public java.lang.Integer getWorkshop() {
		return getInt("workshop");
	}

	/**
	 * 产线编号
	 */
	public M setNo(java.lang.String no) {
		set("no", no);
		return (M)this;
	}
	
	/**
	 * 产线编号
	 */
	public java.lang.String getNo() {
		return getStr("no");
	}

	/**
	 * 产线名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 产线名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 是否显示
	 */
	public M setIsShow(java.lang.Boolean isShow) {
		set("is_show", isShow);
		return (M)this;
	}
	
	/**
	 * 是否显示
	 */
	public java.lang.Boolean getIsShow() {
		return getBoolean("is_show");
	}

	/**
	 * 文件
	 */
	public M setFileUrl(java.lang.String fileUrl) {
		set("file_url", fileUrl);
		return (M)this;
	}
	
	/**
	 * 文件
	 */
	public java.lang.String getFileUrl() {
		return getStr("file_url");
	}

	/**
	 * 状态
	 */
	public M setStatu(java.lang.Integer statu) {
		set("statu", statu);
		return (M)this;
	}
	
	/**
	 * 状态
	 */
	public java.lang.Integer getStatu() {
		return getInt("statu");
	}

	/**
	 * 测试字典:1=哈哈,2=嘿嘿
	 */
	public M setTestStatu(java.lang.Integer testStatu) {
		set("test_statu", testStatu);
		return (M)this;
	}
	
	/**
	 * 测试字典:1=哈哈,2=嘿嘿
	 */
	public java.lang.Integer getTestStatu() {
		return getInt("test_statu");
	}

	/**
	 * 创建者ID
	 */
	public M setCreateUserId(java.lang.String createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	/**
	 * 创建者ID
	 */
	public java.lang.String getCreateUserId() {
		return getStr("create_user_id");
	}

	/**
	 * 创建者姓名
	 */
	public M setCreateUserName(java.lang.String createUserName) {
		set("create_user_name", createUserName);
		return (M)this;
	}
	
	/**
	 * 创建者姓名
	 */
	public java.lang.String getCreateUserName() {
		return getStr("create_user_name");
	}

	public M setCreateDate(java.util.Date createDate) {
		set("create_date", createDate);
		return (M)this;
	}
	
	public java.util.Date getCreateDate() {
		return get("create_date");
	}

	/**
	 * 创建时间
	 */
	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
