package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRpShiftLeader<M extends BaseRpShiftLeader<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 班长姓名
	 */
	public M setShiftLeader(java.lang.String shiftLeader) {
		set("shift_leader", shiftLeader);
		return (M)this;
	}
	
	/**
	 * 班长姓名
	 */
	public java.lang.String getShiftLeader() {
		return getStr("shift_leader");
	}

	/**
	 * 班长工号
	 */
	public M setShiftLeaderJobNo(java.lang.String shiftLeaderJobNo) {
		set("shift_leader_job_no", shiftLeaderJobNo);
		return (M)this;
	}
	
	/**
	 * 班长工号
	 */
	public java.lang.String getShiftLeaderJobNo() {
		return getStr("shift_leader_job_no");
	}

	/**
	 * 班长所在车间的序号
	 */
	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	/**
	 * 班长所在车间的序号
	 */
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 车间
	 */
	public M setWorkshop(java.lang.String workshop) {
		set("workshop", workshop);
		return (M)this;
	}
	
	/**
	 * 车间
	 */
	public java.lang.String getWorkshop() {
		return getStr("workshop");
	}

	/**
	 * 部门
	 */
	public M setDepartment(java.lang.String department) {
		set("department", department);
		return (M)this;
	}
	
	/**
	 * 部门
	 */
	public java.lang.String getDepartment() {
		return getStr("department");
	}

}
