package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseS6sImpeach<M extends BaseS6sImpeach<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * rease
	 */
	public M setReaseJobNo(java.lang.String reaseJobNo) {
		set("rease_job_no", reaseJobNo);
		return (M)this;
	}
	
	/**
	 * rease
	 */
	public java.lang.String getReaseJobNo() {
		return getStr("rease_job_no");
	}

	/**
	 * 问题描述
	 */
	public M setProblem(java.lang.String problem) {
		set("problem", problem);
		return (M)this;
	}
	
	/**
	 * 问题描述
	 */
	public java.lang.String getProblem() {
		return getStr("problem");
	}

	/**
	 * 图片
	 */
	public M setPicture(java.lang.String picture) {
		set("picture", picture);
		return (M)this;
	}
	
	/**
	 * 图片
	 */
	public java.lang.String getPicture() {
		return getStr("picture");
	}

	/**
	 * 审核结果：0=待审核，1=同意，2=拒绝
	 */
	public M setCheckStatus(java.lang.Integer checkStatus) {
		set("check_status", checkStatus);
		return (M)this;
	}
	
	/**
	 * 审核结果：0=待审核，1=同意，2=拒绝
	 */
	public java.lang.Integer getCheckStatus() {
		return getInt("check_status");
	}

	/**
	 * 处理结果：0=待处理，1=同意，2=拒绝
	 */
	public M setHandleStatus(java.lang.Integer handleStatus) {
		set("handle_status", handleStatus);
		return (M)this;
	}
	
	/**
	 * 处理结果：0=待处理，1=同意，2=拒绝
	 */
	public java.lang.Integer getHandleStatus() {
		return getInt("handle_status");
	}

	/**
	 * 发起时间
	 */
	public M setDateTime(java.util.Date dateTime) {
		set("date_time", dateTime);
		return (M)this;
	}
	
	/**
	 * 发起时间
	 */
	public java.util.Date getDateTime() {
		return get("date_time");
	}

}
