package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseRpLineStructure<M extends BaseRpLineStructure<M>> extends Model<M> implements IBean {

	/**
	 * 序号
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 序号
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 产线名称
	 */
	public M setProductionLine(java.lang.String productionLine) {
		set("productionLine", productionLine);
		return (M)this;
	}
	
	/**
	 * 产线名称
	 */
	public java.lang.String getProductionLine() {
		return getStr("productionLine");
	}

	/**
	 * 上级id
	 */
	public M setPid(java.lang.Integer pid) {
		set("pid", pid);
		return (M)this;
	}
	
	/**
	 * 上级id
	 */
	public java.lang.Integer getPid() {
		return getInt("pid");
	}

	/**
	 * 负责人姓名
	 */
	public M setLeaderName(java.lang.String leaderName) {
		set("leader_name", leaderName);
		return (M)this;
	}
	
	/**
	 * 负责人姓名
	 */
	public java.lang.String getLeaderName() {
		return getStr("leader_name");
	}

	/**
	 * 负责人工号
	 */
	public M setLeaderId(java.lang.String leaderId) {
		set("leader_id", leaderId);
		return (M)this;
	}
	
	/**
	 * 负责人工号
	 */
	public java.lang.String getLeaderId() {
		return getStr("leader_id");
	}

}
