package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDataTask<M extends BaseDataTask<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * 状态:0=停止,1=启动
	 */
	public M setState(java.lang.Integer state) {
		set("state", state);
		return (M)this;
	}
	
	/**
	 * 状态:0=停止,1=启动
	 */
	public java.lang.Integer getState() {
		return getInt("state");
	}

	/**
	 * 名称
	 */
	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	/**
	 * 名称
	 */
	public java.lang.String getName() {
		return getStr("name");
	}

	/**
	 * 表达式
	 */
	public M setExp(java.lang.String exp) {
		set("exp", exp);
		return (M)this;
	}
	
	/**
	 * 表达式
	 */
	public java.lang.String getExp() {
		return getStr("exp");
	}

	/**
	 * 实现类
	 */
	public M setClazz(java.lang.String clazz) {
		set("clazz", clazz);
		return (M)this;
	}
	
	/**
	 * 实现类
	 */
	public java.lang.String getClazz() {
		return getStr("clazz");
	}

	/**
	 * 说明
	 */
	public M setInfo(java.lang.String info) {
		set("info", info);
		return (M)this;
	}
	
	/**
	 * 说明
	 */
	public java.lang.String getInfo() {
		return getStr("info");
	}

}
