package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDataField<M extends BaseDataField<M>> extends Model<M> implements IBean {

	/**
	 * ID
	 */
	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ID
	 */
	public java.lang.Integer getId() {
		return getInt("id");
	}

	/**
	 * object_id
	 */
	public M setDataObjectId(java.lang.Integer dataObjectId) {
		set("data_object_id", dataObjectId);
		return (M)this;
	}
	
	/**
	 * object_id
	 */
	public java.lang.Integer getDataObjectId() {
		return getInt("data_object_id");
	}

	/**
	 * 排序索引
	 */
	public M setOrderNum(java.lang.Integer orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}
	
	/**
	 * 排序索引
	 */
	public java.lang.Integer getOrderNum() {
		return getInt("order_num");
	}

	/**
	 * 英文名
	 */
	public M setEn(java.lang.String en) {
		set("en", en);
		return (M)this;
	}
	
	/**
	 * 英文名
	 */
	public java.lang.String getEn() {
		return getStr("en");
	}

	/**
	 * 中文名
	 */
	public M setCn(java.lang.String cn) {
		set("cn", cn);
		return (M)this;
	}
	
	/**
	 * 中文名
	 */
	public java.lang.String getCn() {
		return getStr("cn");
	}

	/**
	 * 主键是否自增长
	 */
	public M setIsAuto(java.lang.Boolean isAuto) {
		set("is_auto", isAuto);
		return (M)this;
	}
	
	/**
	 * 主键是否自增长
	 */
	public java.lang.Boolean getIsAuto() {
		return getBoolean("is_auto");
	}

	/**
	 * 控件类型
	 */
	public M setType(java.lang.String type) {
		set("type", type);
		return (M)this;
	}
	
	/**
	 * 控件类型
	 */
	public java.lang.String getType() {
		return getStr("type");
	}

	/**
	 * 控件配置
	 */
	public M setTypeConfig(java.lang.String typeConfig) {
		set("type_config", typeConfig);
		return (M)this;
	}
	
	/**
	 * 控件配置
	 */
	public java.lang.String getTypeConfig() {
		return getStr("type_config");
	}

	/**
	 * 排列
	 */
	public M setAlign(java.lang.String align) {
		set("align", align);
		return (M)this;
	}
	
	/**
	 * 排列
	 */
	public java.lang.String getAlign() {
		return getStr("align");
	}

	/**
	 * 是否可查询
	 */
	public M setIsQuery(java.lang.Boolean isQuery) {
		set("is_query", isQuery);
		return (M)this;
	}
	
	/**
	 * 是否可查询
	 */
	public java.lang.Boolean getIsQuery() {
		return getBoolean("is_query");
	}

	/**
	 * 是否可显示
	 */
	public M setIsShow(java.lang.Boolean isShow) {
		set("is_show", isShow);
		return (M)this;
	}
	
	/**
	 * 是否可显示
	 */
	public java.lang.Boolean getIsShow() {
		return getBoolean("is_show");
	}

	/**
	 * 是否禁用
	 */
	public M setIsDisable(java.lang.Boolean isDisable) {
		set("is_disable", isDisable);
		return (M)this;
	}
	
	/**
	 * 是否禁用
	 */
	public java.lang.Boolean getIsDisable() {
		return getBoolean("is_disable");
	}

	/**
	 * 是否可排序
	 */
	public M setIsOrder(java.lang.Boolean isOrder) {
		set("is_order", isOrder);
		return (M)this;
	}
	
	/**
	 * 是否可排序
	 */
	public java.lang.Boolean getIsOrder() {
		return getBoolean("is_order");
	}

	/**
	 * 是否可新增
	 */
	public M setIsAdd(java.lang.Boolean isAdd) {
		set("is_add", isAdd);
		return (M)this;
	}
	
	/**
	 * 是否可新增
	 */
	public java.lang.Boolean getIsAdd() {
		return getBoolean("is_add");
	}

	/**
	 * 是否可修改
	 */
	public M setIsUpdate(java.lang.Boolean isUpdate) {
		set("is_update", isUpdate);
		return (M)this;
	}
	
	/**
	 * 是否可修改
	 */
	public java.lang.Boolean getIsUpdate() {
		return getBoolean("is_update");
	}

	/**
	 * 是否可行内修改
	 */
	public M setIsLineUpdate(java.lang.Boolean isLineUpdate) {
		set("is_line_update", isLineUpdate);
		return (M)this;
	}
	
	/**
	 * 是否可行内修改
	 */
	public java.lang.Boolean getIsLineUpdate() {
		return getBoolean("is_line_update");
	}

	/**
	 * 是否可修改数据校验
	 */
	public M setUpdateValidate(java.lang.String updateValidate) {
		set("update_validate", updateValidate);
		return (M)this;
	}
	
	/**
	 * 是否可修改数据校验
	 */
	public java.lang.String getUpdateValidate() {
		return getStr("update_validate");
	}

	/**
	 * 是否可编辑
	 */
	public M setIsEdit(java.lang.Boolean isEdit) {
		set("is_edit", isEdit);
		return (M)this;
	}
	
	/**
	 * 是否可编辑
	 */
	public java.lang.Boolean getIsEdit() {
		return getBoolean("is_edit");
	}

	/**
	 * 是否必填
	 */
	public M setIsRequired(java.lang.Boolean isRequired) {
		set("is_required", isRequired);
		return (M)this;
	}
	
	/**
	 * 是否必填
	 */
	public java.lang.Boolean getIsRequired() {
		return getBoolean("is_required");
	}

	/**
	 * 是否多选项
	 */
	public M setIsMultiple(java.lang.Boolean isMultiple) {
		set("is_multiple", isMultiple);
		return (M)this;
	}
	
	/**
	 * 是否多选项
	 */
	public java.lang.Boolean getIsMultiple() {
		return getBoolean("is_multiple");
	}

	/**
	 * 是否虚拟字段
	 */
	public M setIsFictitious(java.lang.Boolean isFictitious) {
		set("is_fictitious", isFictitious);
		return (M)this;
	}
	
	/**
	 * 是否虚拟字段
	 */
	public java.lang.Boolean getIsFictitious() {
		return getBoolean("is_fictitious");
	}

	/**
	 * 虚拟字段来源sql
	 */
	public M setFictitiousSql(java.lang.String fictitiousSql) {
		set("fictitious_sql", fictitiousSql);
		return (M)this;
	}
	
	/**
	 * 虚拟字段来源sql
	 */
	public java.lang.String getFictitiousSql() {
		return getStr("fictitious_sql");
	}

	/**
	 * 输入提示
	 */
	public M setPlaceholder(java.lang.String placeholder) {
		set("placeholder", placeholder);
		return (M)this;
	}
	
	/**
	 * 输入提示
	 */
	public java.lang.String getPlaceholder() {
		return getStr("placeholder");
	}

	/**
	 * 格式化
	 */
	public M setFormatter(java.lang.String formatter) {
		set("formatter", formatter);
		return (M)this;
	}
	
	/**
	 * 格式化
	 */
	public java.lang.String getFormatter() {
		return getStr("formatter");
	}

	/**
	 * UI校验表达式
	 */
	public M setValidator(java.lang.String validator) {
		set("validator", validator);
		return (M)this;
	}
	
	/**
	 * UI校验表达式
	 */
	public java.lang.String getValidator() {
		return getStr("validator");
	}

	/**
	 * 默认值表达式
	 */
	public M setDefaulter(java.lang.String defaulter) {
		set("defaulter", defaulter);
		return (M)this;
	}
	
	/**
	 * 默认值表达式
	 */
	public java.lang.String getDefaulter() {
		return getStr("defaulter");
	}

	/**
	 * 控件宽度
	 */
	public M setWidth(java.lang.Integer width) {
		set("width", width);
		return (M)this;
	}
	
	/**
	 * 控件宽度
	 */
	public java.lang.Integer getWidth() {
		return getInt("width");
	}

	/**
	 * 控件高度
	 */
	public M setHeight(java.lang.Integer height) {
		set("height", height);
		return (M)this;
	}
	
	/**
	 * 控件高度
	 */
	public java.lang.Integer getHeight() {
		return getInt("height");
	}

	/**
	 * 配置
	 */
	public M setConfig(java.lang.String config) {
		set("config", config);
		return (M)this;
	}
	
	/**
	 * 配置
	 */
	public java.lang.String getConfig() {
		return getStr("config");
	}

	/**
	 * 状态：0=正常，10=只读，20=隐藏，50=禁用
	 */
	public M setAddStatus(java.lang.Integer addStatus) {
		set("add_status", addStatus);
		return (M)this;
	}
	
	/**
	 * 状态：0=正常，10=只读，20=隐藏，50=禁用
	 */
	public java.lang.Integer getAddStatus() {
		return getInt("add_status");
	}

	/**
	 * 状态：0=正常，10=只读，20=隐藏，50=禁用
	 */
	public M setUpdateStatus(java.lang.Integer updateStatus) {
		set("update_status", updateStatus);
		return (M)this;
	}
	
	/**
	 * 状态：0=正常，10=只读，20=隐藏，50=禁用
	 */
	public java.lang.Integer getUpdateStatus() {
		return getInt("update_status");
	}

	/**
	 * 数据类型
	 */
	public M setDataType(java.lang.Integer dataType) {
		set("data_type", dataType);
		return (M)this;
	}
	
	/**
	 * 数据类型
	 */
	public java.lang.Integer getDataType() {
		return getInt("data_type");
	}

	/**
	 * 数据类型名称
	 */
	public M setDataTypeName(java.lang.String dataTypeName) {
		set("data_type_name", dataTypeName);
		return (M)this;
	}
	
	/**
	 * 数据类型名称
	 */
	public java.lang.String getDataTypeName() {
		return getStr("data_type_name");
	}

	/**
	 * 整数位长度
	 */
	public M setDataSize(java.lang.Integer dataSize) {
		set("data_size", dataSize);
		return (M)this;
	}
	
	/**
	 * 整数位长度
	 */
	public java.lang.Integer getDataSize() {
		return getInt("data_size");
	}

	/**
	 * 小数位长度
	 */
	public M setDataDecimal(java.lang.Integer dataDecimal) {
		set("data_decimal", dataDecimal);
		return (M)this;
	}
	
	/**
	 * 小数位长度
	 */
	public java.lang.Integer getDataDecimal() {
		return getInt("data_decimal");
	}

}
