package com.ray.common.model.base;
import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * 
 * Generated by JBolt, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseValveDelivery<M extends BaseValveDelivery<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setPartNo(java.lang.String partNo) {
		set("part_no", partNo);
		return (M)this;
	}
	
	public java.lang.String getPartNo() {
		return getStr("part_no");
	}

	public M setPartName(java.lang.String partName) {
		set("part_name", partName);
		return (M)this;
	}
	
	public java.lang.String getPartName() {
		return getStr("part_name");
	}

	public M setDeliveryQty(java.lang.Integer deliveryQty) {
		set("delivery_qty", deliveryQty);
		return (M)this;
	}
	
	public java.lang.Integer getDeliveryQty() {
		return getInt("delivery_qty");
	}

	public M setDeliveryTime(java.util.Date deliveryTime) {
		set("delivery_time", deliveryTime);
		return (M)this;
	}
	
	public java.util.Date getDeliveryTime() {
		return get("delivery_time");
	}

	public M setOperator(java.lang.String operator) {
		set("operator", operator);
		return (M)this;
	}
	
	public java.lang.String getOperator() {
		return getStr("operator");
	}

}
