package com.ray.common.model;

import java.util.List;

import com.jfinal.plugin.activerecord.Db;
import com.ray.common.model.base.BaseDataTask;

/**
 * 
 * Generated by Ray.
 */
@SuppressWarnings("serial")
public class DataTask extends BaseDataTask<DataTask> {
	//建议将dao放在Service中只用作查询 
	public static final DataTask dao = new DataTask().dao();
	//在Service中声明 可直接复制过去使用
	//private DataTask dao = new DataTask().dao();  
	/** 鏆傚仠 **/
	public static final int STATE_STOP = 0;
	/** 杩愯 **/
	public static final int STATE_START = 1;

	public List<DataTask> findByStart(){
		return this.find("select * from data_task where state = 2");
	}
	
	public int updateState(int id, int state){
		return Db.update("update data_task set state = ? where id = ?", state, id);
	}
}
