package com.ray.common.model;

import com.ray.common.model.base.BaseDataButton;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class DataButton extends BaseDataButton<DataButton> {
	//建议将dao放在Service中只用作查询 
	public static final DataButton dao = new DataButton().dao();
	//在Service中声明 可直接复制过去使用
	//private DataButton dao = new DataButton().dao();  
}
