package com.ray.common.model;

import com.ray.common.model.base.BaseFile;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class File extends BaseFile<File> {
	//建议将dao放在Service中只用作查询 
	public static final File dao = new File().dao();
	//在Service中声明 可直接复制过去使用
	//private File dao = new File().dao();  
}
