package com.ray.common.model;

import com.ray.common.model.base.BaseManHour;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class ManHour extends BaseManHour<ManHour> {
	//建议将dao放在Service中只用作查询 
	public static final ManHour dao = new ManHour().dao();
	//在Service中声明 可直接复制过去使用
	//private ManHour dao = new ManHour().dao();  
}
