package com.ray.common.model;

import com.ray.common.model.base.BasePermissions;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class Permissions extends BasePermissions<Permissions> {
	//建议将dao放在Service中只用作查询 
	public static final Permissions dao = new Permissions().dao();
	//在Service中声明 可直接复制过去使用
	//private Permissions dao = new Permissions().dao();  
}
