package com.ray.common.model;

import com.ray.common.model.base.BasePp;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class Pp extends BasePp<Pp> {
	//建议将dao放在Service中只用作查询 
	public static final Pp dao = new Pp().dao();
	//在Service中声明 可直接复制过去使用
	//private Pp dao = new Pp().dao();  
}
