package com.ray.common.model;

import com.ray.common.model.base.BasePpSkillGrades;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class PpSkillGrades extends BasePpSkillGrades<PpSkillGrades> {
	//建议将dao放在Service中只用作查询 
	public static final PpSkillGrades dao = new PpSkillGrades().dao();
	//在Service中声明 可直接复制过去使用
	//private PpSkillGrades dao = new PpSkillGrades().dao();  
}
