package com.ray.common.model;

import com.ray.common.model.base.BaseQrProblem;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class QrProblem extends BaseQrProblem<QrProblem> {
	public static final QrProblem dao = new QrProblem().dao();
}
