package com.ray.common.model;

import com.ray.common.model.base.BaseRationalProposal;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class RationalProposal extends BaseRationalProposal<RationalProposal> {
	//建议将dao放在Service中只用作查询 
	public static final RationalProposal dao = new RationalProposal().dao();
	//在Service中声明 可直接复制过去使用
	//private RationalProposal dao = new RationalProposal().dao();  
}
