package com.ray.common.model;

import com.ray.common.model.base.BaseRoles;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class Roles extends BaseRoles<Roles> {
	//建议将dao放在Service中只用作查询 
	public static final Roles dao = new Roles().dao();
	//在Service中声明 可直接复制过去使用
	//private Roles dao = new Roles().dao();  
}
