package com.ray.common.model;

import com.ray.common.model.base.BaseRolePermission;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class RolePermission extends BaseRolePermission<RolePermission> {
	//建议将dao放在Service中只用作查询 
	public static final RolePermission dao = new RolePermission().dao();
	//在Service中声明 可直接复制过去使用
	//private RolePermission dao = new RolePermission().dao();  
}
