package com.ray.common.model;

import com.ray.common.model.base.BaseRpImproveType;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class RpImproveType extends BaseRpImproveType<RpImproveType> {
	//建议将dao放在Service中只用作查询 
	public static final RpImproveType dao = new RpImproveType().dao();
	//在Service中声明 可直接复制过去使用
	//private RpImproveType dao = new RpImproveType().dao();  
}
