package com.ray.common.model;

import com.ray.common.model.base.BaseRpLineStructure;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class RpLineStructure extends BaseRpLineStructure<RpLineStructure> {
	//建议将dao放在Service中只用作查询 
	public static final RpLineStructure dao = new RpLineStructure().dao();
	//在Service中声明 可直接复制过去使用
	//private RpLineStructure dao = new RpLineStructure().dao();  
}
