package com.ray.common.model;

import com.ray.common.model.base.BaseS6sAwardRecord;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class S6sAwardRecord extends BaseS6sAwardRecord<S6sAwardRecord> {
	//建议将dao放在Service中只用作查询 
	public static final S6sAwardRecord dao = new S6sAwardRecord().dao();
	//在Service中声明 可直接复制过去使用
	//private S6sAwardRecord dao = new S6sAwardRecord().dao();  
}
