package com.ray.common.model;

import com.ray.common.model.base.BaseS6sDistriction;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class S6sDistriction extends BaseS6sDistriction<S6sDistriction> {
	//建议将dao放在Service中只用作查询 
	public static final S6sDistriction dao = new S6sDistriction().dao();
	//在Service中声明 可直接复制过去使用
	//private S6sDistriction dao = new S6sDistriction().dao();  
}
