package com.ray.common.model;

import com.ray.common.model.base.BaseS6sGloves;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class S6sGloves extends BaseS6sGloves<S6sGloves> {
	//建议将dao放在Service中只用作查询 
	public static final S6sGloves dao = new S6sGloves().dao();
	//在Service中声明 可直接复制过去使用
	//private S6sGloves dao = new S6sGloves().dao();  
}
