package com.ray.common.model;

import com.ray.common.model.base.BaseS6sHandlers;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class S6sHandlers extends BaseS6sHandlers<S6sHandlers> {
	//建议将dao放在Service中只用作查询 
	public static final S6sHandlers dao = new S6sHandlers().dao();
	//在Service中声明 可直接复制过去使用
	//private S6sHandlers dao = new S6sHandlers().dao();  
}
