package com.ray.common.model;

import com.ray.common.model.base.BaseS6sImpeach;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class S6sImpeach extends BaseS6sImpeach<S6sImpeach> {
	//建议将dao放在Service中只用作查询 
	public static final S6sImpeach dao = new S6sImpeach().dao();
	//在Service中声明 可直接复制过去使用
	//private S6sImpeach dao = new S6sImpeach().dao();  
}
