package com.ray.common.model;

import com.ray.common.model.base.BaseS6sKpiTarget;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class S6sKpiTarget extends BaseS6sKpiTarget<S6sKpiTarget> {
	//建议将dao放在Service中只用作查询 
	public static final S6sKpiTarget dao = new S6sKpiTarget().dao();
	//在Service中声明 可直接复制过去使用
	//private S6sKpiTarget dao = new S6sKpiTarget().dao();  
}
