package com.ray.common.model;

import com.ray.common.model.base.BaseS6sPrizeList;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class S6sPrizeList extends BaseS6sPrizeList<S6sPrizeList> {
	//建议将dao放在Service中只用作查询 
	public static final S6sPrizeList dao = new S6sPrizeList().dao();
	//在Service中声明 可直接复制过去使用
	//private S6sPrizeList dao = new S6sPrizeList().dao();  
}
