package com.ray.common.model;

import com.ray.common.model.base.BaseS6sTotal;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class S6sTotal extends BaseS6sTotal<S6sTotal> {
	//建议将dao放在Service中只用作查询 
	public static final S6sTotal dao = new S6sTotal().dao();
	//在Service中声明 可直接复制过去使用
	//private S6sTotal dao = new S6sTotal().dao();  
}
