package com.ray.common.model;

import com.ray.common.model.base.BaseUserRole;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class UserRole extends BaseUserRole<UserRole> {
	//建议将dao放在Service中只用作查询 
	public static final UserRole dao = new UserRole().dao();
	//在Service中声明 可直接复制过去使用
	//private UserRole dao = new UserRole().dao();  
}
