package com.ray.common.model;

import com.ray.common.model.base.BaseValveDelivery;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class ValveDelivery extends BaseValveDelivery<ValveDelivery> {
	//建议将dao放在Service中只用作查询 
	public static final ValveDelivery dao = new ValveDelivery().dao();
	//在Service中声明 可直接复制过去使用
	//private ValveDelivery dao = new ValveDelivery().dao();  
}
