package com.ray.common.model;

import com.ray.common.model.base.BaseValvePartType;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class ValvePartType extends BaseValvePartType<ValvePartType> {
	//建议将dao放在Service中只用作查询 
	public static final ValvePartType dao = new ValvePartType().dao();
	//在Service中声明 可直接复制过去使用
	//private ValvePartType dao = new ValvePartType().dao();  
}
