package com.ray.common.model;

import com.ray.common.model.base.BaseValveParts;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class ValveParts extends BaseValveParts<ValveParts> {
	//建议将dao放在Service中只用作查询 
	public static final ValveParts dao = new ValveParts().dao();
	//在Service中声明 可直接复制过去使用
	//private ValveParts dao = new ValveParts().dao();  
}
