package com.ray.common.model;

import com.ray.common.model.base.BaseValveInventory;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class ValveInventory extends BaseValveInventory<ValveInventory> {
	//建议将dao放在Service中只用作查询 
	public static final ValveInventory dao = new ValveInventory().dao();
	//在Service中声明 可直接复制过去使用
	//private ValveInventory dao = new ValveInventory().dao();  
}
