package com.ray.common.model;

import com.ray.common.model.base.BaseYwTest;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class YwTest extends BaseYwTest<YwTest> {
	//建议将dao放在Service中只用作查询 
	public static final YwTest dao = new YwTest().dao();
	//在Service中声明 可直接复制过去使用
	//private YwTest dao = new YwTest().dao();  
}
