package com.ray.common.model;

import com.ray.common.model.base.BaseYwTestSon;

/**
 * 
 * Generated by JBolt.
 */
@SuppressWarnings("serial")
public class YwTestSon extends BaseYwTestSon<YwTestSon> {
	//建议将dao放在Service中只用作查询 
	public static final YwTestSon dao = new YwTestSon().dao();
	//在Service中声明 可直接复制过去使用
	//private YwTestSon dao = new YwTestSon().dao();  
}
